### ISSUE TITLE
Please Mr. jaysonlong

### ISSUE THREAD

**Issue by raafat-ops** [jaysonlong/webvideo-downloader#49] opened 2021-01-02 13:15 UTC
Please Mr. jaysonlong
When I download Drama from iq.com, Some of the videos durations are not as the durations of them at the site, What's the problem here?

**Comment by jaysonlong** [comment] 2021-01-03 13:32
Duplicate of #43

**Comment by raafat-ops** [comment] 2021-01-03 14:25
Thank you Mr. jaysonlong, you're a genius
Thanks, sir.

**Closed** 2021-01-10 05:30 UTC
