### ISSUE TITLE
未下载 WETV 字幕

### ISSUE THREAD

**Issue by Angu0083** [jaysonlong/webvideo-downloader#157] opened 2023-01-02 16:24 UTC
脚本无法下载 wetv.vip 子磁贴。

Listening on port 18888 for clients...

Receive: {
    "fileName": "EP8: Inheritors - Watch HD Video Online - WeTV",
    "linksurl": "https://ltsaws.wetvinfo.com/svp_50112/01BE2907376FE9635EA5429088C4632054A75CF706E96C61F1B29D763D0D8F843A4BAD5E97C884304BBC01B342CE420730A743E454C068FED40F2F0E9D3FAAC8528D5ED27A0A0E0B87CDCD06CF1CDB5D5CA9FC75673A96E86D47BB9195B7EEA8596504B577792BDB98127682766461A0B7E99FB987FF9454E8DEB5083DCB643769/gzc_1000102_0b53ieaawaaaeaaa7sxawfrmaqodbngqadsa.f323013.ts.m3u8?ver=4|English|https://subtitle.wetvinfo.com/svp_50112/Fr6AtqWu_AAAn-Y0W-oEQQDymZK2N3G1ncUhh4BVKGojO2blwQbuXnNrXNnlMQ5f8FY1zVnmFcBlJYEfrgp0GACwTH8DTZjgHRSsfd8zLX64mm5v8_qNr1lfQnLgtEYVIfVAf3vTXSso1fGz65Fkdw/gzc_1000102_0b53ieaawaaaeaaa7sxawfrmaqodbngqadsa.f864103.vtt.m3u8?ver=4|Indonesian|https://subtitle.wetvinfo.com/lQmcxO4QQTOyiw5Wy3BpfecNCHnLTvG3v0hs1xtrOYhttZU6lZdjUREoU8mHxeOI8ylpUnrHKt3qb0rxHk4sax2LrF9XfrT2sanMlmxeXDbgBrVwjafkkq5yEHNK5X3uf70WtDwG3Hh7ypvLQlxO4w/e0034mdvsvs.53004.vtt.m3u8?ver=4",
    "data": "...",
    "type": "link"
}

Handle: "EP8: Inheritors - Watch HD Video Online - WeTV"

匹配到309段视频，开始下载
-- dispatcher/downloadHls
并行8线程下载
进度: [########################################] 100%    325.0/-MB  1.9MB/s 51s  
正在合并视频
匹配到2个字幕，开始下载
并行8线程下载
进度: [########################################] 100%      0.0/-MB    0KB/s 2s  
正在集成字幕

**Comment by jaysonlong** [comment] 2023-02-06 09:31
Duplicate of #135

**Closed** 2023-02-06 09:32 UTC
